class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: lstcondensation.model.LSGraphTCN
    init_args:
      node_indim: 9
      edge_indim: 3
      h_dim: 256
      e_dim: 256
      h_outdim: 12
      L_hc: 5
      ec:
        class_path: gnn_tracking.models.edge_classifier.ECFromChkpt
        init_args:
          ec_class_name: gnn_tracking.training.ec.ECModule
          ec_chkpt_path: /home/kl5675/Documents/23/git_sync/lst-condensation-hackathon/scripts/lightning_logs/prompt-nonchalant-swift/checkpoints/epoch=195-step=117600.ckpt
      ec_thld: 0.1
  lw_repulsive: 0.7
  lw_background: 0.
  background_loss: null
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials:
        class_path: gnn_tracking.postprocessing.clusterscanner.PulsedNTrials
        init_args:
          warmup_epoch: 6
          low_trials: 6
          high_trials: 12
          high_every: 3
          warmup_trials: 0
      n_jobs: 3
      min_samples_range: [1, 1]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
