class_path: gnn_tracking.training.ec.ECModule
init_args:
  model:
    class_path: gnn_tracking.models.edge_filter.EFMLP
    init_args:
      node_indim: 9
      edge_indim: 3
      hidden_dim: 128
      depth: 3
  loss_fct:
    class_path: gnn_tracking.metrics.losses.EdgeWeightBCELoss
    init_args:
      pt_thld: 0.9
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
